# Generated by Django 3.1.1 on 2020-09-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('image', models.ImageField(null=True, upload_to='%Y/%m/%d')),
                ('age', models.CharField(max_length=6, null=True, verbose_name='result')),
                ('resultage', models.CharField(max_length=6, null=True, verbose_name='result')),
                ('compareyesterday', models.CharField(max_length=6, null=True, verbose_name='result')),
                ('skincolor', models.CharField(max_length=12, null=True, verbose_name='result')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': 'tizen_mirror_aianalysis',
                'verbose_name_plural': 'tizen_mirror_aianalysis',
                'db_table': 'tizen_mirror_aianalysis',
            },
        ),
    ]
